// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7DVgUeU2N8sKB7NwjI_5Lo5DuPccocCc',
    appId: '1:637371460162:web:0aadcb935b82b1c2825bdb',
    messagingSenderId: '637371460162',
    projectId: 'fashion-app-e5728',
    authDomain: 'fashion-app-e5728.firebaseapp.com',
    storageBucket: 'fashion-app-e5728.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ZKP0aY-O7omCSKuDRR61cvLdZ-1KUOs',
    appId: '1:637371460162:android:e1f4ae7e923c9e7a825bdb',
    messagingSenderId: '637371460162',
    projectId: 'fashion-app-e5728',
    storageBucket: 'fashion-app-e5728.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNjxG6VpoDjp0nEeL1uZYh5tGCyg3MHlY',
    appId: '1:637371460162:ios:4207ea8641cd3397825bdb',
    messagingSenderId: '637371460162',
    projectId: 'fashion-app-e5728',
    storageBucket: 'fashion-app-e5728.appspot.com',
    iosClientId: '637371460162-m59qp1l79rd53gnbhfsubc6o5i5alesr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNjxG6VpoDjp0nEeL1uZYh5tGCyg3MHlY',
    appId: '1:637371460162:ios:69782c1285a23ac1825bdb',
    messagingSenderId: '637371460162',
    projectId: 'fashion-app-e5728',
    storageBucket: 'fashion-app-e5728.appspot.com',
    iosClientId: '637371460162-dfsiofv3hb2amgnha26cr98n3ige9j9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionApp.RunnerTests',
  );
}
